1. Data Collection
2. Data Cleaning
3. EDA
4. Feature Engineering
5. Encoding & Scaling
6. Model Building (multiple algorithms)
7. Evaluation
8. Hyperparameter Tuning
9. Final Model Selection
10.pipeline- ONE SINGLE MODEL
11.Deployment

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_excel("Telco_customer_churn.xlsx")
df

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [17]:
df["Count"].nunique()

1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [7]:
## CLTV - Customer Lifetime Value -- This gives the value about how long the customer was associated. 
## This may leak the data while testing

In [9]:
df["Country"].value_counts()

Country
United States    7043
Name: count, dtype: int64

In [11]:
df["State"].value_counts()

State
California    7043
Name: count, dtype: int64

In [13]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [21]:
drop_cols = ['CustomerID', 'Count', 'Country', 'State',
       'Lat Long', 'Latitude', 'Longitude',  'Churn Label', 
       'Churn Score', 'CLTV', 'Churn Reason']
df=df.drop(columns=drop_cols)

In [23]:
df.shape

(7043, 22)

In [25]:
df["Total Charges"]=pd.to_numeric(df["Total Charges"],errors="coerce")

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Gender             7043 non-null   object
 3   Senior Citizen     7043 non-null   object
 4   Partner            7043 non-null   object
 5   Dependents         7043 non-null   object
 6   Tenure Months      7043 non-null   int64
 7   Phone Service      7043 non-null   object
 8   Multiple Lines     7043 non-null   object
 9   Internet Service   7043 non-null   object
 10  Online Security    7043 non-null   object
 11  Online Backup      7043 non-null   object
 12  Device Protection  7043 non-null   object
 13  Tech Support       7043 non-null   object
 14  Streaming TV       7043 non-null   object
 15  Streaming Movies   7043 non-null   object
 16  Contract           7043 non-null   object
 17  Paperless Billing  7043 non-null   object
 18  Payment Method     7043 non-null   object
 19  Monthly Charges    7043 non-null   float64
 20  Total Charges      7032 non-null   float64
 21  Churn Value        7043 non-null   int64
dtypes: float64(2), int64(3), object(17)
memory usage: 1.2+ MB

In [31]:
### KNN imputer for missing values in Total Charges

In [33]:
from sklearn.impute import KNNImputer

In [37]:
knn_imputer=KNNImputer(n_neighbors=5)
df[["Total Charges"]]=knn_imputer.fit_transform(df[["Total Charges"]])

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Gender             7043 non-null   object
 3   Senior Citizen     7043 non-null   object
 4   Partner            7043 non-null   object
 5   Dependents         7043 non-null   object
 6   Tenure Months      7043 non-null   int64
 7   Phone Service      7043 non-null   object
 8   Multiple Lines     7043 non-null   object
 9   Internet Service   7043 non-null   object
 10  Online Security    7043 non-null   object
 11  Online Backup      7043 non-null   object
 12  Device Protection  7043 non-null   object
 13  Tech Support       7043 non-null   object
 14  Streaming TV       7043 non-null   object
 15  Streaming Movies   7043 non-null   object
 16  Contract           7043 non-null   object
 17  Paperless Billing  7043 non-null   object
 18  Payment Method     7043 non-null   object
 19  Monthly Charges    7043 non-null   float64
 20  Total Charges      7043 non-null   float64
 21  Churn Value        7043 non-null   int64
dtypes: float64(2), int64(3), object(17)
memory usage: 1.2+ MB

In [41]:
### EDA
df.describe()

,Zip Code,Tenure Months,Monthly Charges,Total Charges,Churn Value
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,93521.964646,32.371149,64.761692,2283.300441,0.265370
std,1865.794555,24.559481,30.090047,2265.000258,0.441561
min,90001.000000,0.000000,18.250000,18.800000,0.000000
25%,92102.000000,9.000000,35.500000,402.225000,0.000000
50%,93552.000000,29.000000,70.350000,1400.550000,0.000000
75%,95351.000000,55.000000,89.850000,3786.600000,1.000000
max,96161.000000,72.000000,118.750000,8684.800000,1.000000

In [43]:
### from above mean and median are almost same that means the data is normally distributed and that too symmetric(std)

In [53]:
cat_cols=df.select_dtypes(include=["object","category"]).columns
for col in cat_cols:
    print(f"{col} : {df[col].nunique()}")

City : 1129
Gender : 2
Senior Citizen : 2
Partner : 2
Dependents : 2
Phone Service : 2
Multiple Lines : 3
Internet Service : 3
Online Security : 3
Online Backup : 3
Device Protection : 3
Tech Support : 3
Streaming TV : 3
Streaming Movies : 3
Contract : 3
Paperless Billing : 2
Payment Method : 4

In [55]:
### City - freq
### Binary - label/map function
### three and 4 classes - label

In [59]:
freq=df["City"].value_counts()
df["City"]=df["City"].map(freq)

In [67]:
binary_col=["Gender",
"Senior Citizen",
"Partner",
"Dependents",
"Phone Service",
"Paperless Billing"]
for col in binary_col:
    print(df[col].value_counts())

Gender
Male      3555
Female    3488
Name: count, dtype: int64
Senior Citizen
No     5901
Yes    1142
Name: count, dtype: int64
Partner
No     3641
Yes    3402
Name: count, dtype: int64
Dependents
No     5416
Yes    1627
Name: count, dtype: int64
Phone Service
Yes    6361
No      682
Name: count, dtype: int64
Paperless Billing
Yes    4171
No     2872
Name: count, dtype: int64

In [71]:
binary_col=["Gender",
"Senior Citizen",
"Partner",
"Dependents",
"Phone Service",
"Paperless Billing"]
for col in binary_col:
    df[col]=df[col].map({"Yes":1,"No":0,"Male":1,"Female":0})
    df[col]=pd.to_numeric(df[col],errors="coerce")

In [75]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
cat_cols=df.select_dtypes(include=["object","category"]).columns
for col in cat_cols:
    df[col]=le.fit_transform(df[col])

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   int64
 1   Zip Code           7043 non-null   int64
 2   Gender             7043 non-null   int64
 3   Senior Citizen     7043 non-null   int64
 4   Partner            7043 non-null   int64
 5   Dependents         7043 non-null   int64
 6   Tenure Months      7043 non-null   int64
 7   Phone Service      7043 non-null   int64
 8   Multiple Lines     7043 non-null   int32
 9   Internet Service   7043 non-null   int32
 10  Online Security    7043 non-null   int32
 11  Online Backup      7043 non-null   int32
 12  Device Protection  7043 non-null   int32
 13  Tech Support       7043 non-null   int32
 14  Streaming TV       7043 non-null   int32
 15  Streaming Movies   7043 non-null   int32
 16  Contract           7043 non-null   int32
 17  Paperless Billing  7043 non-null   int64
 18  Payment Method     7043 non-null   int32
 19  Monthly Charges    7043 non-null   float64
 20  Total Charges      7043 non-null   float64
 21  Churn Value        7043 non-null   int64
dtypes: float64(2), int32(10), int64(10)
memory usage: 935.5 KB

In [79]:
X=df.drop("Churn Value",axis=1)
y=df["Churn Value"]

In [83]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [85]:
### Scaling
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
## Model building